variable "compose_version" {
  type    = string
}

variable "maven_version" {
  type    = string
}

variable "client_id" {
  type    = string
}

variable "client_secret" {
  type    = string
}

variable "location" {
  type    = string
}

variable "resource_group_name" {
  type    = string
}

variable "subscription_id" {
  type    = string
}

locals {
  now_unix_timestamp = formatdate("YYYYMMDDhhmmss",timestamp())
}

source "azure-arm" "autogenerated_1" {
  azure_tags = {
    imagetype = "jenkins-agent-ubuntu18.04"
    timestamp = "${local.now_unix_timestamp}"
  }
  client_id                         = "${var.client_id}"
  client_secret                     = "${var.client_secret}"
  image_offer                       = "UbuntuServer"
  image_publisher                   = "Canonical"
  image_sku                         = "18.04-LTS"
  location                          = "${var.location}"
  managed_image_name                = "jenkins-agent-ubuntu1804"
  managed_image_resource_group_name = "${var.resource_group_name}"
  os_type                           = "Linux"
  subscription_id                   = "${var.subscription_id}"
  vm_size                           = "Standard_DS2_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    environment_vars = ["MAVEN_VERSION=${var.maven_version}", "COMPOSE_VERSION=${var.compose_version}"]
    execute_command  = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    script           = "./scripts/ubuntu-18-provision.sh"
  }

  post-processor "manifest" {
    output     = "manifest.json"
    strip_path = true
  }
}
