maven_version               = "3.8.1"
git_version                 = "2.33.0"
jdk11_version               = "11.0.11+9"
jdk8_version                = "8u292-b10"
git_lfs_version             = "2.13.3"
compose_version             = "1.29.2"
openssh_authorized_keys_url = "https://raw.githubusercontent.com/jenkins-infra/aws/main/ec2_agents_authorized_keys"
