maven_version               = "3.8.1"
git_version                 = "2.32.0"
jdk11_version               = "11.0.11+9"
jdk8_version                = "8u292-b10"
git_lfs_version             = "2.12.1"
compose_version             = "1.25.4"
openssh_version             = "v8.1.0.0p1-Beta"
openssh_authorized_keys_url = "https://raw.githubusercontent.com/jenkins-infra/aws/main/ec2_agents_authorized_keys"
