---
title: "Bump Docker Compose version"

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  dockerComposeVersion:
    kind: githubRelease
    name: Get the latest Docker Compose version
    spec:
      owner: "docker"
      repository: "compose"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionFilter:
        ## Semver removes any 'v' prefix and get the latest version following semantic
        kind: semver
        ## Only check for 1.x.y versions
        pattern: "~1"

targets:
  updateDockerComposeVersion:
    name: Update the DockerCompose version in the Packer default values
    kind: file
    spec:
      file: ".auto.pkrvars.hcl"
      matchPattern: 'compose_version(.*)=.*'
      replacePattern: 'compose_version$1= "{{ source `dockerComposeVersion` }}"'
    scmID: default

pullrequests:
  default:
    kind: github
    scmID: default
    targets:
      - updateDockerComposeVersion
    spec:
      labels:
        - dependencies
