---
title: "Bump Docker Compose version"
sources:
  dockerComposeVersion:
    kind: githubRelease
    name: Get the latest Docker Compose version
    spec:
      owner: "docker"
      repository: "compose"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionFilter:
        kind: semver
        pattern: "~1"
targets:
  updateDockerComposeVersion:
    name: Update the DockerCompose version in the Packer default values
    kind: file
    spec:
      file: ".auto.pkrvars.hcl"
      matchPattern: 'compose_version(.*)=.*'
      replacePattern: 'compose_version$1= "{{ source `dockerComposeVersion` }}"'
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
