---
name: Bump Docker Compose version

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastReleaseVersion:
    kind: githubrelease
    name: Get the latest Docker Compose version
    spec:
      owner: "docker"
      repository: "compose"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionfilter:
        kind: semver
    transformers:
      - trimprefix: v

targets:
  updateDockerComposeVersion:
    name: Update the `DockerCompose` version in the Packer default values
    kind: yaml
    spec:
      file: "provisioning/tools-versions.yml"
      key: "compose_version"
    scmid: default
  updateVersionInGoss:
    name: Update the `DockerCompose` version in the goss test
    kind: yaml
    spec:
      files:
        - goss/goss-linux.yaml
        - goss/goss-windows.yaml
      key: $.command.docker_compose.stdout[0]
    scmid: default

actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Bump Docker Compose version to {{ source "lastReleaseVersion" }}
    spec:
      labels:
        - enhancement
        - docker-compose
