
data "amazon-ami" "autogenerated_1" {
  filters = {
    name                = "ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  region      = "${var.location}"
}

variable "location" {
  type    = string
}

variable "compose_version" {
  type    = string
}

variable "maven_version" {
  type    = string
}

locals {
  now_unix_timestamp = formatdate("YYYYMMDDhhmmss",timestamp())
}

source "amazon-ebs" "autogenerated_1" {
  ami_name      = "jenkins-agent-ubuntu18.04-amd64-${local.now_unix_timestamp}"
  instance_type = "t2.micro"
  launch_block_device_mappings {
    delete_on_termination = true
    device_name           = "/dev/sda1"
    volume_size           = 100
    volume_type           = "gp2"
  }
  region       = "${var.location}"
  source_ami   = "${data.amazon-ami.autogenerated_1.id}"
  ssh_username = "ubuntu"
  tags = {
    imageplatform = "amd64"
    imagetype     = "jenkins-agent-ubuntu18.04"
    timestamp     = "${legacy_isotime("20060102150405")}"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    environment_vars = ["MAVEN_VERSION=${var.maven_version}", "COMPOSE_VERSION=${var.compose_version}"]
    execute_command  = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    script           = "./scripts/ubuntu-18-provision.aws.amd64.sh"
  }

  post-processor "manifest" {
    output     = "manifest.json"
    strip_path = true
  }
}
