---
- name: Install the Jenkins agent common requirements
  ansible.builtin.apt:
    name:
      - make
      - unzip
      - zip
      - parallel
      - yamllint
      # Provides the xmllint binary
      - libxml2-utils
      - bc
    state: present
    install_recommends: false
    update_cache: true
